services:
  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    network_mode: host
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:1337x@localhost/data_engineering_test
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /home/amonmugo/PROJECTS/data_engineering:/home/amonmugo/PROJECTS/data_engineering
      - /home/amonmugo/.dbt:/home/amonmugo/.dbt
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username airflow
        --password 123456789
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com || true &&
      airflow webserver
      "
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    network_mode: host
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:1337x@localhost/data_engineering_test
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /home/amonmugo/PROJECTS/data_engineering:/home/amonmugo/PROJECTS/data_engineering
      - /home/amonmugo/.dbt:/home/amonmugo/.dbt
    command: airflow scheduler
    restart: always
